# Site settings
title: Frank Elavsky
email: fje@cmu.edu
address: Pittsburgh, PA
description: > # this means to ignore newlines until "baseurl:"
   PhD at Carnegie Mellon University investigating accessibility and data interaction. Previously: data interaction R&D at Apple and staff software engineer at Visa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.frank.computer" # the base hostname & protocol for your site
production_url: "https://www.frank.computer"
github_username: frankelavsky
permalink: /blog/:year/:month/:title.html

twitter:
  username: frankelavsky

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
